version: '1'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    volumes:
      - "./init/selenoid/browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4441:4444"
    network_mode: bridge

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8087:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
